"""add payment risk assessment

Revision ID: b15a5639483b
Revises: 1f6835725260
Create Date: 2026-08-18 16:38:52.240455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15a5639483b'
down_revision: Union[str, Sequence[str], None] = '1f6835725260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('risk_score', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('risk_level', sa.String(length=20), nullable=False))
    op.add_column('payments', sa.Column('risk_reasons', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'risk_reasons')
    op.drop_column('payments', 'risk_level')
    op.drop_column('payments', 'risk_score')
    # ### end Alembic commands ###
