"""add refunds

Revision ID: d382cdb9260a
Revises: ee6b9d434181
Create Date: 2026-08-12 19:47:15.775267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd382cdb9260a'
down_revision: Union[str, Sequence[str], None] = 'ee6b9d434181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ledger_transaction_type = postgresql.ENUM(
    "capture",
    "refund",
    name="ledger_transaction_type",
    create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('completed', name='refund_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=True)
    ledger_transaction_type.create(op.get_bind(), checkfirst=True,)
    op.add_column("ledger_transactions", sa.Column("transaction_type", ledger_transaction_type, nullable=False,))
    op.drop_constraint(op.f('ledger_transactions_payment_id_key'), 'ledger_transactions', type_='unique')
    op.create_index(op.f('ix_ledger_transactions_payment_id'), 'ledger_transactions', ['payment_id'], unique=False)
    op.create_unique_constraint('uq_ledger_transaction_payment_type', 'ledger_transactions', ['payment_id', 'transaction_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ledger_transaction_payment_type', 'ledger_transactions', type_='unique')
    op.drop_index(op.f('ix_ledger_transactions_payment_id'), table_name='ledger_transactions')
    op.create_unique_constraint(op.f('ledger_transactions_payment_id_key'), 'ledger_transactions', ['payment_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('ledger_transactions', 'transaction_type')
    ledger_transaction_type.drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_table('refunds')
    # ### end Alembic commands ###
