"""add payment idempotency

Revision ID: de43b13192ee
Revises: 259ed5190e57
Create Date: 2026-08-12 13:27:57.232078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de43b13192ee'
down_revision: Union[str, Sequence[str], None] = '259ed5190e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('request_hash', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_payments_merchant_idempotency_key', 'payments', ['merchant_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payments_merchant_idempotency_key', 'payments', type_='unique')
    op.drop_column('payments', 'request_hash')
    op.drop_column('payments', 'idempotency_key')
    # ### end Alembic commands ###
