"""add double entry ledger

Revision ID: ee6b9d434181
Revises: de43b13192ee
Create Date: 2026-08-12 15:25:09.692736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6b9d434181'
down_revision: Union[str, Sequence[str], None] = 'de43b13192ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('processor_clearing', 'merchant_payable', name='ledger_account_type'), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('merchant_id', name='uq_ledger_accounts_merchant')
    )
    op.execute(
    """
    INSERT INTO ledger_accounts (
        id,
        code,
        account_type,
        merchant_id
    )
    VALUES (
        '00000000-0000-0000-0000-000000000001',
        'processor_clearing',
        'processor_clearing',
        NULL
    )
    """
)
    op.create_table('ledger_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('debit', 'credit', name='ledger_entry_direction'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_ledger_entries_positive_amount'),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
    """
    INSERT INTO ledger_accounts (
        id,
        code,
        account_type,
        merchant_id
    )
    SELECT
        gen_random_uuid(),
        'merchant:' || id::text,
        'merchant_payable',
        id
    FROM merchants
    """
    )
    
    op.create_index(op.f('ix_ledger_entries_account_id'), 'ledger_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_transaction_id'), 'ledger_entries', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_transaction_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_account_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('ledger_transactions')
    op.drop_table('ledger_accounts')
    # ### end Alembic commands ###
